### ISSUE TITLE
How are you bro !!! 

### ISSUE THREAD

**Issue by sambitsingha** [Sayan-001/Fake-Face-Detection-Model#1]
# Chatting in Github issues 
## lol XD

**Comment by Sayan-001** [comment]
Nice (⁠◕⁠ᴥ⁠◕⁠)

**Comment by sambitsingha** [comment]
Now we will talk in GitHub issues XD

**Comment by sambitsingha** [comment]
@Sayan-001 Damn it , you should have closed the issue.
